# wrangler.toml
# 这是 Cloudflare Workers 的配置文件

# 项目名称（必须唯一，Cloudflare 后台会用到）
name = "ps1"

# 入口文件
main = "_worker.js"

# 兼容性日期（一般填成你写代码的日期）
compatibility_date = "2025-08-31"

# 环境变量，可以在代码里通过 env.API_KEY 获取
[vars]
UUID = "18432cd2-4812-42e6-a500-c1bb190ba65a"
TR_PASS = "aY*%2]bXZ^_3$RnK"
SUB_PATH = "2_AeZ_VIoFDwNdb1"

# KV 绑定（如果你有多个 KV，可以写多个 [[kv_namespaces]]）
[[kv_namespaces]]
binding = "kv"   # 代码里用 env.KV 调用
id = "bfd57163a16b4871aae65c2fb9659fb2"  # 这里填你 Cloudflare KV 的空间 ID
